### ISSUE TITLE
far pointers?

### ISSUE THREAD

**Issue by stsp** [alexfru/SmallerC#13]
Hi!

It is explicitly stated in the docs that the
far pointers are unsupported. Yet its a pity,
as it prevents the building of many existing
DOS projects with this compiler.
So I'd like to know if the support is planned,
and if not - why, and how difficult is it to add
such a support? Given that the huge pointers
are already supported, what is the remaining
problems that prevents the support of the far
pointers?

**Comment by stsp** [comment]
> I may create a special memory model in which all pointers are far.

Yes, this is what I had in mind myself.
I've seen the code inside your compiler that
converts the flat pointers to seg:off, and I thought
how simple it might be to convert far pointer to
seg:off instead. I don't think I have a lot of DOS
code that uses huge pointers, but far pointers are
very common it seems.

> In order to compile old DOS C code you will have to extend the library

But extending the library is just a routine work when
the compiler supports everything you need. :)

> Finding those 16-bit ints that must remain 16-bit has not been fun.

Maybe adding a switch to limit the int size can help?
After all, on 64bit arches the int was left fixed to 32bit,
so such practice does exist.
In either case, I am sure you have thought off all those
simple possibilities, and, according to your reply, you are
not overly satisfied with them.

> Does this answer your question?

Many thanks for an answer!
To be honest, the complexity behind the problem is
still not entirely outlined, but the compilers are exceptionally
complex to program, so I am not going to demand a full details. :)
I only wanted to try to build an fdkernel with this.

**Comment by alexfru** [comment]
> I only wanted to try to build an fdkernel with this.

You wouldn't like the size or speed. :)

> the complexity behind the problem is still not entirely outlined, but the compilers are exceptionally complex to program

The most complex part of a C compiler is the optimizer and the rest is _just a routine work_. :) Smaller C doesn't have an optimizer, but simple ≠ easy/cheap/quick. Someone needs to write and test the code.

> Maybe adding a switch to limit the int size can help?

It can't. A switch that does nothing or removes a lot of functionality (as is the case in the tiny and small memory models, where ints are 16-bit) is not what you want. Is it? :) There needs to be some new code behind that switch.

Recall that char and short types are ints for most intents and purposes with the only difference from ints being in their size and range. I only have to do something special for chars and shorts when I read them from a variable or when I store something to a char or short variable (or cast to char/short). IOW, except those few operations I can handle chars, shorts and ints using the same machine-word-sized ALU instructions. I can handle pointers in very much the same way as well if I don't need to deal with segmentation or pointers larger than the machine word. And this is what I do in the compiler. I have ALU operations on ints, I pass and return ints and I have only one flavor of the switch statement, for ints. There really is just one type under the hood of the compiler. Imagine that. Think about it for a second.

What you're suggesting is effectively introducing a new long type that when combined in expressions with smaller types (char, short, int) would work the same way as int works when combined with even smaller types (char, short). It would nearly double the size of the expression evaluator and the code generator. It's not something terribly complex, but it is a lot of work. A lot of code will need to be thrown away and rewritten because it's not very suited for the kind of extension you're asking.

There really is just one type under the hood.

Does this explain the situation?

**Comment by stsp** [comment]
OK, so essentially I think your are saying that
having the pointer types larger than int is quite
difficult in your compiler because you work with
ints even when dealing with the pointers.
I can understand that. :)
So it seems far pointers will appear in your compiler
somewhere near the introduction of the long types to
the 16bit memory models, which is currently not
planned.
Pretty clear, thanks for you time!

**Comment by alexfru** [comment]
Yep, something like that.
