### ISSUE TITLE
Using long and float types in 16-bit mode

### ISSUE THREAD

**Issue by ZeroKelvinKeyboard** [alexfru/SmallerC#15]
Hey,

I'm working on a MikeOS C library and I'm having trouble with the lack of `long` type that is needed for some functions. It would also be nice to support floating point in `printf` and other C functions. Do you have any plans to add the long or float types for 16-bit binaries?

If not, perhaps you could explain the problems and I'll try to implement it.

By the way, I've notice that using a floating point operation in 16-bit mode causes the compiler to emit a symbol such as: __addsf3

Could I add floating point support at a library level by providing my own functions for these symbols? 

Thanks

**Comment by alexfru** [comment]
For the reasons why the things are the way they are and for the kinds of changes needed to make them what they aren't see #13.Let me ask you a question in return.

**Comment by ZeroKelvinKeyboard** [comment]
Let's see if I understand this properly:
The Smaller C compiler benefits from the simplicity of only having one "type" internally and adding a long type to 16-bit mode would make parsing more complex and a lot of code would have to be rewritten.
Is that right?

With regards to your query on MikeOS, I don't think it's possible to do unreal mode. The loading would require non-trivial modifications the MikeOS disk code, which probably wouldn't get accepted into the project anyway. A bigger problem would be having 32-bit addresses and integers would break compatibility with nearly all the MikeOS API for one reason or another.

I don't really want to have to switch to using 32-bit addresses/integers, I just want to be able to use a 32-bit type for a few functions. I guess it's not possible?

**Comment by alexfru** [comment]
Supporting 32-bit types in 16-bit models is not about parsing. Parsing is a done deal. It's about all the extra type checks and conversions in the common part of the compiler and supporting longer types (as register pairs or as 32-bit registers) in the x86 code generator. There's no code for that and I have no plans for adding it in the near future.

As for MikeOS, I don't mean augmenting it to understand .EXE files. I mean the physical ability to read arbitrary parts of large files. This is sufficient. You can have a tiny loader app that would load a large .EXE and run it. But for that it needs to be able to read all of the .EXE in small chunks. That's my point. If you don't like unreal mode(l) or are concerned about it working in a VM, there's huge model. I believe this can be implemented fairly quickly and I can help with it.

One problem with the approach I'm talking about is that the tiny loader app needs to either be passed the name of the .EXE (does MikeOS provide any such functionality, I mean, command line arguments?) or it needs to have the .EXE name hard-coded in it and once hard-coded, you won't be able to rename the .EXE at your will without recompiling or patching the tiny loader. There's also a bit of ugliness here, having two parts of every .EXE-based app. But it should still work.

What do you say?

**Comment by ZeroKelvinKeyboard** [comment]
Okay, so no long types, that much is clear.

I really don't understand what you are getting at with this MikeOS idea. Even if you could load parts of larger files in MikeOS (which you can't without non-trivial modifications) what's the advantage? It not that I don't like unreal mode, I'm just not sure how a program would continue to run after entering it. You would need a 32-bit version of the operating system with a 32-bit API to support the now 32-bit program.

The huge model would not work either since MikeOS is designed to use an (almost) tiny memory model. 

You can definitely make a loader and pass arguments over the command line. The rest I'm afraid, is going to require further explanation.

**Comment by alexfru** [comment]
Oops, I should've explained what was obvious to me but not necessarily to someone else. Sorry.

The reason why I keep mentioning large files is that the huge and unreal model .EXEs are larger. That's because they use 32-bit types and therefore have their integers and pointers take twice as much space and also the code that manipulates them is larger as well. Oh, and there are relocations in these .EXEs. So, these huge/unreal .EXEs may run out of the 32KB that MikeOS provides to apps much quicker than mostly 16-bit code in tiny/small model.

The idea is that the tiny loader app would load the .EXEs not into the 64KB segment containing the loader and MikeOS, but beyond that since there's quite a bit of unused memory (unless you're really running an ancient PC with less than 640KB of RAM).

Or is that somehow not Kosher or insufficiently retro? Mind you, Smaller C generates 80386 instructions even in small model, so with Smaller C you're not in the 80806-80286 world anymore.

Naturally, there would need to be some wrappers around MikeOS system calls to make things work. Similar to what you've already done but mainly making sure that the data exchange is happening within those 32KB where the loader resides, so there are no surprises for MikeOS. (Btw, DPMI .EXEs compiled by Smaller C do the same since DOS is limited to accessing ~1MB of RAM but DPMI apps can have their data located above 1MB, so there's a file buffer below 1MB that DOS can access and fread() copies data to/from it before/after invoking DOS int 0x21.)

Huge model is just a way of representing and dealing with far pointers (not very efficient, but very C-programmer-friendly). It doesn't need any special support from the CPU or VM. It works in DOS and Windows just fine.

Unreal mode(l), OTOH, does need a 80386 CPU and it needs it in real mode (not protected or virtual 8086) so it can tweak the CPU mode a little to drop the 64KB segment limits to, again, simplify work with far pointers (and also be able to access all of 4GB or RAM). This won't work in Windows or in DOS with certain memory managers/drivers loaded. And some VMs may not support this, although, I think all the major ones should be just fine because many OSes use unreal mode at boot time in order to access 4GB of memory while retaining access to BIOS services.

Did this help?

**Comment by ZeroKelvinKeyboard** [comment]
I think so.

It's an interesting idea. I have created a new 32-bit branch of my project to investigate it. Not very much progress on it so far, as there's still a lot to figure out about unreal mode and adapting the calling conventions. I imagine they have to go something like this:
1) Copy any needed strings/data to a local memory pool.
2) Enter 16-bit mode (how???)
3) Retrieve parameters off the stack same as before.
4) Call function.
5) Re-enable unreal mode.
6) Copy any needed strings/data to far buffers.

This all seems pretty cumbersome, and probably has a large overhead. I'll have to look into how DOS managed to do it. Is there a trick to getting in and out of unreal mode? It seems affect instruction decoding by being a 32-bit mode. At the very least it would be a good idea to replace some of the less complicated OS functions with C equivalents. 

Unfortunately larger programs will have to wait for now. There's just no easy way to do it. Instead I'm working on modifying the `__start` routine to enter unreal mode and copy the rest of the program above the 1 MiB mark. Programs will still be 32 KiB limited but have access to plenty of memory, floats, longs, etc.

I'll see how it goes. I suppose the Github issues section may not be the best place to discuss the project. 

Thanks for your help.

**Comment by alexfru** [comment]
The unreal mode I'm talking about functions as real mode for the most part and there's no need to enter/leave/enable/disable it on every transition between the code that uses it and any other code that doesn't. It simply allows one to use offsets larger than 0xFFFF, e.g. you can do something like this in your otherwise normal 16-bit real mode:
~~~
push word 0
pop ds
mov eax, 0xFFFFF ; 1MB-1
mov al, [eax] ; read a byte just below 1MB
~~~
The last two instructions are 80386 instructions, but they work in 16-bit mode just as well (look up address size- and operand size override prefixes). The extra instruction prefixes and the longer instruction operands are what makes unreal (and huge) mode code larger.

I advise against using the kind of unreal mode where code is 32-bit as in 32-bit protected mode. It makes compatibility with 16-bit code (of BIOS, DOS, MikeOS, whatever) harder and it may not work in some VMs (e.g. DOSBox). You'll have to do mode transitions with it and, I think, you'll have to run such code with interrupts disabled, which you shouldn't do for long intervals of time, meaning, you'll have to enable them once in a while. Don't go there.

**Comment by ZeroKelvinKeyboard** [comment]
Hey Alex,
Is what you're describing actually possible?

So here's the problem, do or do I not load a 32-bit code selector?
On the [OSDev Wiki article](http://wiki.osdev.org/Unreal_Mode) it defines two modes, big unreal mode and huge unreal mode. In the latter you do use 32-bit code and in the former you don't.

If I do load a 32-bit code selector (huge unreal mode):
 * It is possible to run code from any 32-bit address.
 * 16-bit code does not work (MikeOS, DOS, BIOS, etc)

If I only change the data selector (big unreal mode):
 * Code must run in a 16-bit address space.
 * Everything remains compatible.

Feel free to correct me, (I'd love to be wrong here) but it seems like I can't load above 1 MiB **and** use 16-bit code. What does SmallerC's `-unreal` flag expect?

Little confused sorry,
Zero

**Comment by alexfru** [comment]
The -unreal and -dosu options in Smaller C generate code for the first kind of unreal mode described on that page. Therefore, it's compatible with 16-bit real mode code but code (and stack) must be below 1MB, although all other data may be anywhere. The startup code for unreal mode in Smaller C (c0du.asm) takes care of setting up unreal mode. Neither DOS nor MikeOS need to do anything about it.

**Comment by ZeroKelvinKeyboard** [comment]
Actually, I do need to do something about it. While it's true I'm building the libraries with `-unreal` (previously `-tiny`), the final program is built with `-flat16`. I'm producing a flat binary not a DOS EXE I **do** need to have my own startup code.

Speaking of `-flat16` it doesn't seem to produce the correct code any more. All the library code is fine but the main application doesn't pass to it correctly. Is there a way I can produce unreal mode code but keep my output as a flat binary and not a DOS EXE?

**Comment by alexfru** [comment]
Flat unreal executables won't work because the linker has special handling of relocations in unreal .EXEs. The linker creates the .relod section at link time for unreal .EXEs and c0du.asm uses the .relot and .relod sections to perform relocations before running the C library initialization and main(). This special handling is obviously not done when linking flat executables, and so your flat binary will lack information essential to correct operation.

On top of that you should know how much memory is needed for the executable, which may be anything up to 576KB (the linker limits code+data in huge/unreal .EXEs to 512KB and then there's up to 64KB of stack; the remaining 640KB-576KB=64KB is presumed to be taken by the OS). A flat executable won't provide you any of this info (e.g. you won't know the size of the .bss section after the end of the file and you won't know the stack size that the program wants).

Also the entry point should naturally be far. Various hacks to make the first byte of the file the entry point make little sense when there's potentially more than 64KB of code.

And then I don't think you can debug flat binaries in MikeOS. But you can debug .EXEs in DOS.

It's time to grow a notch and ditch flat executables for anything other than what they're normally used for, that is, tiny model programs.

Loading DOS .EXEs is easy. Especially the ones produced by Smaller C. Don't be afraid. Load the file at offset 0 of some segment, check the MZ signature in the header, get the CS:IP and SS:SP from the header, adjust those CS and SS by the segment into which you loaded the file. And you should know what to do next with these CS:IP and SS:SP.

Here's an excerpt of the relevant part of my FAT boot loader:
~~~
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Type detection, .COM or .EXE? ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

        push    byte ImageLoadSeg
        pop     ds
        mov     ax, ds                  ; ax=ds=seg the file is loaded to

        cmp     word [0], 5A4Dh         ; "MZ" signature?

        je      RelocateEXE             ; yes, it's an EXE program

; Code for .COMs is skipped as not relevant.

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Relocate, setup and run a .EXE program ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

RelocateEXE:

        add     ax, [08h]               ; ax = image base

; There are no DOS-style relocations in .EXEs produced by Smaller C,
; so, the relocation code is removed as not relevant.

RelocationDone:

        mov     bx, ax
        add     bx, [0Eh]
        mov     ss, bx                  ; ss for EXE
        mov     sp, [10h]               ; sp for EXE

        add     ax, [16h]               ; cs
        push    ax
        push    word [14h]              ; ip
Run:

; Code for passing the BIOS boot disk and loading magic numbers
; is removed as not relevant.

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; All done, transfer control to the program now ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
        retf
~~~

I don't have size checks in the loader, but they shouldn't be hard to do. The minimum that a DOS .EXE needs is the size of the file (there's a number of 512-byte "pages" in the .EXE header) and the minimum memory needed beyond the end of the file (in 16-byte paragraphs, also in the .EXE header; there's also the maximum, but it's set to the same value by Smaller C and is probably completely irrelevant).

There are also some differences in coding for unreal vs tiny models. Not too many. At C level it's just that ints are 32-bit and pointers are flat 32-bit. At asm level there's obviously more, but we'll get there when we get there.

**Comment by ZeroKelvinKeyboard** [comment]
Time to leave the simple world of flat binaries then! I hope this is useful.

This format doesn't seem too tricky at least. I generated a DOS EXE with the `-unreal` option and put a simple wrapper around it based on the code you provided so it could be loaded as a flat binary. It ran right up until my `__start` code attempted to call the MikeOS API. There's definitely a lot to rewrite there. The OS API wrappers should probably be stored in the MikeOS segment with the loader since  the compiler is going to generate far calls.

Speaking of `__start`, you mentioned there's code that SmallerC will put inside the program to setup unreal mode and do the relocations. I'm guessing I shouldn't be redefining it `__start`? What would I do instead, for OS specific startup code that needs to come before `main`? Where can I put it so it will be executed as well as the compiler's start code? Do I need to pass any variables to the compiler's start code? What about the argv and argc?

**Comment by alexfru** [comment]
If you need to pass some info from whatever code that starts the unreal .EXE, here's how you can modify c0du.asm:

~~~
...
__start: 
    push    es 
    push    ds 
    pushfd 
    push    ebp 
    push    edi 
    push    esi 
    push    edx 
    push    ecx 
    push    ebx 
    push    eax 
    call    .labnext 
... 
    xor     ebx, ebx 
    mov     bx, ss 
    shl     ebx, 4 
    movzx   eax, sp 
    add     ebx, eax 
    push    ebx ; push the address of the reg structure 
    ; Call __start__(), which will set up argc and argv for main() and call exit(main(argc, argv))
    db      0x9A
.patch_start_addr:
    dd      ___start__
    ; __start__() shouldn't return
...
~~~

And then \_\_start\_\_() will take a pointer to the structure containing registers:
~~~
typedef struct
{
  unsigned eax, ebx, ecx, edx, esi, edi, ebp, eflags;
  unsigned short ds, es;
} start_regs;
~~~

And from there it can figure out stuff like command line arguments and what not and then perform any additional initialization and pass the arguments to main().

**Comment by ZeroKelvinKeyboard** [comment]
Ah, so I could have just used the stack? I assumed it wasn't preserved. In the end managed to pass data between the loader and the start-up code by putting the page offset of a structure in the FS register.

Looking at the code in c0du.asm, I figured out my initialisation code needs to be under the label `___start__` to be called by the `__start` code in c0du.asm. Apparently this code also wants me to have the label `___Irq5Isr` but I'm not sure what should be in there, so I've left it as a stub for now. Could you provide any insight into this?

This loader seems to be working pretty well now, but I'm having trouble calling `_main` from `___start__`. I tried to do so with a near call, however the target location ends up wrong.

Can I get some help with the calling conventions used in the unreal model?
 * Are all numeric types and return values 32-bits?
 * It seems like data addresses are flat 32-bit values, is that correct? 
 * How do I call C functions in the unreal model? I'm trying to call `main()` in C from `___start__` in assembly.
 * What all the segments used for? Is it okay if I use FS and GS?

**Comment by alexfru** [comment]
The stack is balanced throughout c0du.asm.

I wanted to reenable unreal mode automatically if it gets disabled. If it's disabled, IOW, if you're back in real mode, accessing data at offsets higher than 0xFFFF in any segment will trigger a #GP. And a #GP handler can reenable unreal mode. That's the idea. However, #GP and IRQ5 handlers are on the same vector 0xd. So, if you also want to use IRQ5 (e.g. for Sound Blaster interrupts or something like that), you need to distinguish between the two. To distinguish between the two the handler code looks at two things: whether the #GP/IRQ5 handler is entered recursively (there's a counter, Int0xdIsrDepth) and whether IRQ5 is marked as in-service in the interrupt controller. The first entrance can be due to any of the two causes. The second entrance can only be due to #GP. You can just keep \_\_Irq5Isr() as is if you're not going to handle IRQ5 yourself. Or you can remove it and all the code that calls it:
~~~
    xor     ax, ax
    mov     ds, ax
    mov     es, ax                  ; ds=es=0 for 32-bit flat addresses in __Irq5Isr()

    db      0x9A
.patch_irq5isr_addr:
    dd      ___Irq5Isr
    ; Does __Irq5Isr() want us to call the old ISR?
    or      eax, eax
    jz      .irq5done
~~~
Also to be removed with it:
~~~
    dd      ___Int0xdIsr.patch_irq5isr_addr ; patch the far call to __Irq5Isr()
~~~

You should probably write \_\_start\_\_() in C to simplify things.
In general, in unreal mode, every direct call needs to be far, e.g.:
~~~
    ; Call __start__(), which will set up argc and argv for main() and call exit(main(argc, argv))
    db      0x9A
.patch_start_addr:
    dd      ___start__
~~~
This is a far call instruction with an absolute address (seg:ofs) encoded in it. The label .patch_start_addr is referenced from the .relot section (see at the end of the file) in order for relocation to know where to adjust/patch addresses in memory. The relocation code (at the beginning of the file) will adjust the address encoded this instruction. It will first make it correct physical and then transform it into correct segment:offset pair. All direct calls in C are done in this fashion (look at the generated assembly code).

All numeric and pointer types are passed and returned as 32-bit (unsigned char/short being zero-extended, signed char/short being sign-extended to 32 bits). Passing is through the stack. Returning is through the EAX register.

DS and ES must be zero for C code to work. Make sure you clear them after e.g. calling BIOS/MikeOS services.

FS and GS are free to use, although I see no point in using them. It defeats the purpose of unreal mode, doesn't it?

**Comment by ZeroKelvinKeyboard** [comment]
I was using FS and GS as segment that always point to the operating system's local data. However, I've ditched this in favour of your earlier idea of pushing a `struct` from the loader onto the stack containing pointers to the data. It be unwise to mess with any operating system segments anyway.jj

It's been quite a struggle to get used to the new assembly. Everything to do with data addresses has to have some kind of 32-bit size override so you end up with weird things like `push dword [dword address]` or `a32 lodsb`. I used some macros to abstract away some of the annoying things like calls.

I'm getting the hang of it though thanks to your help and some trial and error. For this kind of debugging, the bochs debugger is very useful, especially with its step through and magic breakpoint. I hope to finish rewriting the OS wrappers soon.

Which bring my to a few more questions. How would I refer to an absolute address in the data segment? Do I need something tricky like with the unreal mode calls?

Also, what is required to implement floating point values? I assuming I'm going to need some kind of float to ASCII routine plus its opposite. Do I need my own floating point conversion or add/sub/mul/div routines? Does the compiler provide any built in functions that will help with implementing the maths library? 

Thanks,
Zero

**Comment by alexfru** [comment]
Does the generated assembly code for the below answer your first question?
~~~
int v = (int)&v;

int f(int s)
{
  if (s == 0)
    return (int)&v;
  v = s;
  return v;
}
~~~
Or do you need something else?

The compiler will generate calls to the functions in x87.c for +, -, \*, /, f-p compare and f-p\<-\>int conversion. Things like sin(), log() are in their respective files.

Decimal f-p support exists only for printf(). There's still no decimal f-p support in scanf(). atof() and strtod() are not implemented. The compiler has this functionality internally for parsing f-p constants, but I wouldn't put that code into the library (it's grossly inefficient). The thing is, conversion between decimal and binary f-p is tricky.

**Comment by ZeroKelvinKeyboard** [comment]
With regards to the generated assembly code, I was more looking for corner cases that could potentially cause problems later on. The `.relod` section is one such source of confusion. Is it just used for function pointers?

There's definitely a need for a good floating point conversion. I do remember trying to build such a thing at some point. Let's see what we can put together when I've got the MikeOS C library up and running!

Another idea that I'd like to try is a self hosting implementation. Smaller C seems ideal for this, since the binaries are not huge and for the most part use only standard library functions (apart from the pre-processor in the 'ucpp' directory). I'd be interesting to actually be able to compile C on MikeOS and it's derivatives. There are still plenty of barriers to that though, like having an assembler and being able to load larger programs.

**Comment by alexfru** [comment]
The .relod section is used for all relocations as I indicated earlier and explained it in the comments in c0du.asm. If an instruction refers to an address of a variable (or another instruction) in a non-IP-relative fashion and you want the instruction to work irrespective of where it ends up loaded in RAM, you must relocate. Period. This is the same in all CPU modes on all CPUs. Nothing new or unusual here.

The .relot section is used to convert code addresses into segment:offset pairs to facilitate far calls to allow for more than 64KB of code in 16-bit mode. Again, nothing conceptually new here on x86. In unreal mode of Smaller C the startup code first processes .relod to figure out where things are located and then it processes .relot to turn some of those addresses (which were subject to relocation with .relod) into seg:ofs pairs. That's all.

About the only caveat here is that 16-bit non-IP-relative relocations won't work. That is, regular near IP-relative conditional and unconditional jumps will work just fine when confined to the same 64KB segment, but other kinds of 16-bit relocations will not and you should not create them. In particular, if you want to create a jump table (e.g. for something similar to the C switch statement), the code needs to be written with this limitation in mind. Currently Smaller C does not generate such jump tables. It creates a series of compares and conditional near IP-relative jumps and thus avoids the problem.

Self hosting Smaller C in [u]real mode anywhere other than DOS is problematic. Only NASM and YASM can assemble code for huge or unreal mode(l)s of Smaller C. FASM can't. And Smaller C won't be able to compile NASM or YASM. There are several options, none of which is very exciting:

- Writing a new assembler
- Emitting object code instead of assembly code (but then what about "inline" asm code?)
- Going into protected mode (but what about the OS and BIOS? use virtual 8086 mode to make it work?)
- Introducing some kind of compatibility with DOS APIs and DPMI to run NASM or YASM

Why not simply use FreeDOS or a protected mode OS? And in the latter case it would probably make more sense to use a different (better) compiler like gcc.

The preprocessor (ucpp) uses only standard C functions by default. Non-standard stuff is under \#ifdefs.

**Comment by ZeroKelvinKeyboard** [comment]
If I only need to support the standard library, I'm already mostly set.

Fortunately I don't need to write a new assembler. As I just remembered, there *is* an assembler for MikeOS: the [asm4mo project](https://github.com/leonardo-ono/asm4mo) created in 2012. Since it was designed for MikeOS, it supports a NASM syntax can handle all ~~80386~~ 8086 instructions and a few assembler directives (e.g. 'db', 'equ', org', etc). This is conveniently the same as Smaller C's output format.

The bad news is also that it was designed for MikeOS and only supports 16-bit instructions, flat binaries and runs in a tiny memory model, which limits the file size it can handle. The source code isn't too difficult to read, so perhaps a few modifications could remove these limitations. Not perfect, but it's good to have a lot of the work already done.

I'll still need to get loading "large" files working in MikeOS and uh, directory support. I should have some experiment code that I wrote a few years ago for this.

As usually happens, there'll probably be something else annoying that'll stand in the way. If you can think of anything, let me know.

**Comment by alexfru** [comment]
asm4mo has bugs and limitations. What's missing: 80386 instructions, ELF object files, support for large files with lots of code and labels (smlrc.c compiles into 70K lines (1.7MB file) of assembly code with 5.4K labels). I doubt you can just tweak asm4mo to get that functionality. It's a throw away and rewrite type of project. Not overly complex, but there's quite some work.

**Comment by ZeroKelvinKeyboard** [comment]
You're right, there a lot of work to be done and it'll all have to be done in assembly. Probably best to rewrite. I was hoping to avoid having to write a new assembler but I will if it's the only option. 

On the other hand I do have a 32-bit C library that I need to test out, so maybe it'll be an interesting project. Having a real project might reveal problems controlled tests cannot. Smaller C's output code looks pretty simple, there's no ifdefs, macros or other preprocessor stuff (unlike my own code, hmm). As long there's support for NASM's code style, 80386 instructions and a few assembler directives it should be fine. 

Looks like there's a lot to be done with the r/m bytes, labels, sections and preprocessor directives. Do I need ELF support? For unreal mode code Smaller C uses it as an intermediate format but doesn't output an ELF file. Could a different format be used?

**Comment by alexfru** [comment]
Why do you think a different format might somehow be better or amount to less work? You'd need to also add support for this other format in the linker, wouldn't you?

**Comment by rofl0r** [comment]
@alexfru is there some documentation you'd recommend that explains all these DOS/x86 weirdo modes in detail with tips and tricks ?

**Comment by alexfru** [comment]
@rofl0r Unreal mode is really real mode with the only difference in segment limits being larger than 64KB. That's all there is to it (and segment limits are well documented, no secret there). Intel officially denies (or tries to) its existence, but you can't deny something that's been in wide use (by the various Microsofts, smaller companies and individuals) for decades. I have a version of their manual, where they mention it as "big real" without ever defining or elaborating on the meaning of the term. Oops.

**Comment by alexfru** [comment]
@ZeroKelvinKeyboard Closing this one?

**Comment by ZeroKelvinKeyboard** [comment]
Sure, my reason for originally opening the issue of getting 32-bit int support and floats is resolved. I should be able to figure the rest out for myself. 

No assembler yet, but I should finish the 32-bit version of my C libraries by the end of the week. 

Thanks for your help! 

_Sent from my Samsung SM-G900I using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
