### ISSUE TITLE
compile error (using clang with asan) 

### ISSUE THREAD

**Issue by frokaikan** [alexfru/SmallerC#20]
I use clang(with fsanitize=address) to compile this project.
when I call $ make
I receive:

awk -v l=/opt/SmallerC/v0100/srclib/ '/[.](c|asm)$/{$0=l$0}{print}' /opt/SmallerC/v0100/srclib/lcds.txt > lcds.op
./smlrcc -SI /opt/SmallerC/v0100/include -I /opt/SmallerC/v0100/srclib @lcds.op

==15851==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 1400 byte(s) in 1 object(s) allocated from:
    #0 0x4da2e0 in realloc (/opt/SmallerC/smlrcc+0x4da2e0)
    #1 0x51445b in fatargs /opt/SmallerC/v0100/smlrcc.c:550:23

SUMMARY: AddressSanitizer: 1400 byte(s) leaked in 1 allocation(s).
/opt/SmallerC/v0100/../common.mk:42: recipe for target 'lcds.a' failed
make: *** [lcds.a] Error 1
rm lcds.op

**Comment by alexfru** [comment]
smlrcc, smlrl, n2f may do a few allocations which aren't freed before termination.
This isn't critical to operation of these programs as they aren't doing lots of allocations and deallocations that would potentially cause out of memory errors (due to depletion of free memory or address space fragmentation). And these programs do not operate continuously.
My simple recommendation is to not use ASAN. It's unlikely to find any problem worthy of attention. The compiler proper, smlrc, does not allocate memory dynamically as of now.

**Comment by alexfru** [comment]
@frokaikan Any progress?

**Comment by frokaikan** [comment]
Ah, I let asan not detect the memory leak and now I could compile it.
Thanks.
