### ISSUE TITLE
Support 32 bit data operations (using stubs) on 16 bit CPUs (small, tiny)

### ISSUE THREAD

**Issue by cocus** [alexfru/SmallerC#31]
Hi!
I started using this compiler again just to prototype some code on the same board I've mentioned again on my other Issue (which is 3 y.o. now!) and this time I hit a snag when trying to use more "heavy" code (like petit FS from ElmChan). 32 bit data storage is extensively used on that codebase; mostly using a typedef for DWORD. I understand that the CPU can't do any 32 bit operations, and stubs for these operations need to be created. But that said, would it be feasible to add these stubs (even unoptimized!) to an existing assembly code (for instance the crt lib) and then make the compiler use these when it encounters a 32 bit operation?
Thanks.

**Comment by alexfru** [comment]
I do not plan to further develop this version of the compiler precisely because it's cumbersome to work around its design limitations.

What you should be able to do instead is use structures or pointers.
For example:
~~~
#include <stdio.h>
typedef unsigned short pair[2];
void add32(pair dst, pair src)
{
  dst[1] += src[1] + (*dst > 0xFFFF - *src);
  *dst += *src;
}
int main(void)
{
  pair a = { 0x0001, 0x0000 };
  pair b = { 0xFFFF, 0xFFFF };
  add32(a, b); // 1 + -1 == 0
  printf("0x%02X%02X", a[1], a[0]);
  return 0;
}
~~~

You can implement multiplication, comparison, shifts, etc etc in this way.
And you can implement add32() and the like in assembly if needed.
