### ISSUE TITLE
What about new architectures?

### ISSUE THREAD

**Issue by mandrookin** [alexfru/SmallerC#49]
Would you like add new architecture for your compiler?

I have virtual machine with some exotic CPU, but have no development tools, except an assembler language.

Of course, there is no one reason for spending your time for this issue, but I should ask for that.

**Comment by alexfru** [comment]
You can try adapting SmallerC or LCC for your architecture. If you need a compiler for your Slagheap, it should be relatively straightforward. The 32-bit MIPS may be similar enough to Slagheap because it's 32-bit and sufficiently uniform so you may use the MIPS as the starting point for the backend/code generator.
I'm not willing to add new architectures to SmallerC at this point.
