### ISSUE TITLE
Not an issue and off-topic to your project, but need help concerning an implmentation...

### ISSUE THREAD

**Issue by ytrezq** [alexfru/SmallerC#6]
Greetings,

I have a problem where I need to [change the enter key](http://stackoverflow.com/q/29213463/2284570 "alternative to the fscanf()/vscanf() functions family for using an alternative validation key or how to create a custom language layout?").
You are one of the rare person which produce a public source code for a standard library which work under dos.
But I still need help about it.

What does the values in[`__chartype__[257]`](https://github.com/alexfru/SmallerC/blob/master/v0100/srclib/ctype.c)correspond to?

Also, I can’t find the code which is responsible for waiting input in [`__doscan()`](https://github.com/alexfru/SmallerC/blob/master/v0100/srclib/doscan.c).
Nor I can find the one which responsible for ending the input on a`\n`.

Sorry for contacting you in this way...

**Comment by alexfru** [comment]
If you're interested in the details of how the library works, you should download the sources and use your favorite file searching tools (findstr, grep, etc) to find where (in which files and on which lines) things like \_\_chartype\_\_\[\] are used and therefore what they mean. I'm not going to do this for you, at least, not everytime you can't find something trivial. Look inside isalnum.c. Read the documentation (C standard, K&R 2nd edition, etc) on the function defined in this file. See other similar functions. However, this variable has nothing to do with your keyboard problem.

There's no waiting done by the library itself. All the waiting occurs inside DOS. \_\_doscan() calls fgetc(), which calls \_\_fillbuf(), which calls read(), which calls DosRead(), which calls function 0x3f of int 0x21, which waits until it the end of line (Enter key) or until the supplied buffer gets full. This is what Microsofts KB113058 tells you about function 0x3f of int 0x21.

Also, JFYI, my compiler and its library require a 80386 CPU. Your device appears to have a 80186 CPU.

The proper way to fix your problem is either to use a regular (or more compatible) keyboard with the device or to write a keyboard driver (a.g. a TSR program) that would intercept interrupts from the keyboard and service them. I believe you could read the scan code and if it's not of the EXE key, let the BIOS finish handling it. Otherwise, if it's EXE, properly translate and write the code(s) corresponding to Enter to the BIOS keyboard queue located in the BIOS Data Area, as if it was Enter, and properly finish handling the interrupt (acknowledge the keyboard, send EOI to the PIC).

I have no intention of writing such a driver for you or teaching you how to write it. It's not overly complex, but you'll have to do it yourself and ask for help elsewhere. This is definitely off-topic for my compiler project.
